[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "18.0.0"
  # You will need to add NEXT_PUBLIC_API_URL in the Netlify Dashboard
